name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x] # Test on LTS + latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. TypeScript compile check
      - name: TypeScript build check
        run: npx tsc --noEmit

      # 5. Run tests with coverage
      - name: Run Jest tests
        run: npm test -- --coverage
      
      # 6. Lint and prettier
      - name: Lint and Format Check
        run: |
          npm run lint
          npm run format -- --check
